app:
  env: dev
  app_name: gin-app
  port: 8000

db:
  driver: mysql # 数据库驱动
  host: 127.0.0.1 # 域名
  port: 3306 # 端口号
  database: go-test # 数据库名称
  username: root # 用户名
  password: M_db@server001 # 密码
  charset: utf8mb4 # 编码格式
  max_idle_conns: 10 # 空闲连接池中连接的最大数量
  max_open_conns: 100 # 打开数据库连接的最大数量
  log_mode: info # 日志级别
  enable_file_log_writer: true # 是否启用日志文件
  log_filename: sql.log # 日志文件名称
  db_name_list: ppc_library,growth
  db_host_write: 47.96.225.173
  db_host_read: 47.96.225.173,47.96.225.173
  db_port_write: 3306
  db_port_read: 3306

  